-- 코드를 입력하세요
SELECT A.CART_ID 
FROM(
    SELECT CP.CART_ID, GROUP_CONCAT(CP.NAME) AS CA
    FROM CART_PRODUCTS CP
    GROUP BY CP.CART_ID
) A
WHERE A.CA LIKE '%Yogurt%' 
AND A.CA LIKE '%Milk%'
ORDER BY A.CART_ID