-- 코드를 입력하세요
SELECT ap.APNT_NO, p.PT_NAME, ap.PT_NO, ap.MCDP_CD, d.DR_NAME, ap.APNT_YMD
FROM APPOINTMENT ap
LEFT JOIN DOCTOR d ON ap.MDDR_ID = d.DR_ID
LEFT JOIN PATIENT p ON ap.PT_NO = p.PT_NO
WHERE ap.APNT_YMD LIKE '2022-04-13%'
    AND ap.APNT_CNCL_YN = 'N'
GROUP BY ap.APNT_NO
ORDER BY ap.APNT_YMD ASC