-- 코드를 작성해주세요
SELECT 
    SUM(HG.SCORE) AS SCORE,
    HE.EMP_NO AS EMP_NO,
    HE.EMP_NAME AS EMP_NAME,
    HE.POSITION AS POSITION,
    HE.EMAIL AS EMAIL
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG ON HG.EMP_NO = HE.EMP_NO
GROUP BY HG.YEAR, HG.EMP_NO
HAVING HG.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1;