-- 코드를 작성해주세요
SELECT 
    HG_TS.TOTAL_SCORE AS SCORE,
    HE.EMP_NO AS EMP_NO,
    HE.EMP_NAME AS EMP_NAME,
    HE.POSITION AS POSITION,
    HE.EMAIL AS EMAIL
FROM HR_EMPLOYEES HE
JOIN (
    SELECT HG.EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE HG
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ORDER BY TOTAL_SCORE DESC
    LIMIT 1
) HG_TS 
ON HG_TS.EMP_NO = HE. EMP_NO