-- 코드를 작성해주세요
SELECT 
    HD.DEPT_ID AS DEPT_ID,
    HD.DEPT_NAME_EN AS DEPT_NAME_EN,
    AVG_SALS.AVG_SAL AS AVG_SAL
FROM HR_DEPARTMENT HD
JOIN (
    SELECT ROUND(AVG(HE.SAL), 0) AS AVG_SAL, HE.DEPT_ID AS DEPT_ID
    FROM HR_EMPLOYEES HE
    GROUP BY DEPT_ID
) AVG_SALS
ON AVG_SALS.DEPT_ID = HD.DEPT_ID
ORDER BY AVG_SAL DESC;
